[workspace]
members = [
    "crates/move-language-server",
    "crates/analysis",
    "crates/move-executor",
    "crates/dialects",
    "crates/dialects/shared",
    "crates/dialects/lang",
    "crates/utils",
    "crates/integration_tests",
    "crates/syntax",
]

[profile.release]
lto = "off"